version: "3.1"

services:
  db:
    image: mongo:6.0.6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: backend-ts
    volumes:
      - ./mongo:/data/db
